DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DisplayName VARCHAR(100) DEFAULT NULL,
    Email VARCHAR(500) DEFAULT NULL,
    EmailVerified BOOLEAN DEFAULT NULL,
    Uid VARCHAR(250) NOT NULL UNIQUE,

    Role INT NOT NULL,
    Provider INT NOT NULL
);
